"""Add exports table

Revision ID: 5c8d9181603e
Revises: 71ca78278cdd
Create Date: 2026-06-05 19:57:22.308517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8d9181603e'
down_revision: Union[str, Sequence[str], None] = '71ca78278cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='exportstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exports')
    # ### end Alembic commands ###
